[package]
name = "john-wick-parse"
version = "6.1.0"
authors = ["Waddlesworth <github@genj.io>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
hex = "0.3"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_derive = "1.0"
erased-serde = "0.3"
aes = "0.7"
block-modes = "0.8"
bitreader = "0.3.1"
glm = "0.2"
image = "0.23"
libloading = "0.5"
flate2 = "1.0"
bit-vec = "0.6"
lazy_static = "1.4.0"
half = "2.4.1"
